<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Orbit/Systems/NativeGhostPolicy.cs" Link="NativeGhostPolicy.cs" />
    <Compile Include="../../Orbit/Systems/NativeGhostSystem.cs" Link="NativeGhostSystem.cs" />
    <Compile Include="../../Orbit.Server/Config/OrbitServerConfig.cs" Link="OrbitServerConfig.cs" />
  </ItemGroup>
</Project>
